New_Solution_Template.WebUI/Areas/Identity/Pages/Account/ExternalLogin.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using New_Solution_Template.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using New_Solution_Template.Services;

namespace New_Solution_Template.WebUI.Areas.Identity.Pages.Account
{
    [AllowAnonymous]
    public class ExternalLoginModel : PageModel
    {
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IAccountService _accountService;
        private readonly ILogger<ExternalLoginModel> _logger;

        public ExternalLoginModel(
            SignInManager<ApplicationUser> signInManager,
            UserManager<ApplicationUser> userManager,
            IAccountService accountService,
            ILogger<ExternalLoginModel> logger)
        {
            _signInManager = signInManager;
            _userManager = userManager;
            _accountService = accountService;
            _logger = logger;
        }

        [BindProperty]
        public InputModel Input { get; set; }

        public string LoginProvider { get; set; }

        public string ReturnUrl { get; set; }

        [TempData]
        public string ErrorMessage { get; set; }

        public class InputModel
        {
            [Required]
            public string FirstName { get; set; }

            [Required]
            public string LastName { get; set; }


        }

        public IActionResult OnGetAsync()
        {
            return RedirectToPage("./Login");
        }

        public IActionResult OnPost(string provider, string returnUrl = null)
        {
            // Request a redirect to the external login provider.
            var redirectUrl = Url.Page("./ExternalLogin", pageHandler: "Callback", values: new { returnUrl });
            var properties = _signInManager.ConfigureExternalAuthenticationProperties(provider, redirectUrl);
            return new ChallengeResult(provider, properties);
        }

        public async Task<IActionResult> OnGetCallbackAsync(string returnUrl = null, string remoteError = null)
        {
            returnUrl = returnUrl ?? Url.Content("~/");
            if (remoteError != null)
            {
                ErrorMessage = $"Error from external provider: {remoteError}";
                return RedirectToPage("./Login", new { ReturnUrl = returnUrl });
            }
            var info = await _signInManager.GetExternalLoginInfoAsync();
            if (info == null)
            {
                ErrorMessage = "Error loading external login information.";
                return RedirectToPage("./Login", new { ReturnUrl = returnUrl });
            }
            if (info.Principal.FindFirst(ClaimTypes.Email).Value.EndsWith("loodos.com") == false)
            {
                ErrorMessage = "Error loading external login information.";
                return RedirectToPage("./Login", new { ReturnUrl = returnUrl });
            }

            // Sign in the user with this external login provider if the user already has a login.
            var result = await _signInManager.ExternalLoginSignInAsync(info.LoginProvider, info.ProviderKey, isPersistent: false, bypassTwoFactor: true);
            if (result.Succeeded)
            {
                _logger.LogInformation("{Name} logged in with {LoginProvider} provider.", info.Principal.Identity.Name, info.LoginProvider);
                return LocalRedirect(returnUrl);
            }
            if (result.IsLockedOut)
            {
                return RedirectToPage("./Lockout");
            }
            else
            {
                // If the user does not have an account, then ask the user to create an account.
                ReturnUrl = returnUrl;
                LoginProvider = info.LoginProvider;
                if (info.Principal.HasClaim(c => c.Type == ClaimTypes.Email))
                {
                    Input = new InputModel();

                }
                return Page();
            }
        }

        public async Task<IActionResult> OnPostConfirmationAsync(string returnUrl = null)
        {
            returnUrl = returnUrl ?? Url.Content("~/");
            // Get the information about the user from the external login provider
            var info = await _signInManager.GetExternalLoginInfoAsync();
            if (info == null)
            {
                ErrorMessage = "Error loading external login information during confirmation.";
                return RedirectToPage("./Login", new { ReturnUrl = returnUrl });
            }

            if (ModelState.IsValid)
            {
                var userEmail = info.Principal.FindFirstValue(ClaimTypes.Email);

                var result = await _accountService.CreateAsync(userEmail, Input.FirstName,Input.LastName, info);

                if (result.Succeeded)
                {
                    var user = await _userManager.FindByEmailAsync(userEmail);
                    await _signInManager.SignInAsync(user, isPersistent: false);
                    _logger.LogInformation("User created an account using {Name} provider.", info.LoginProvider);
                    return LocalRedirect(returnUrl);
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }

            LoginProvider = info.LoginProvider;
            ReturnUrl = returnUrl;
            return Page();
        }
    }
}

New_Solution_Template.WebUI/Areas/Identity/Pages/Account/Login.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using New_Solution_Template.Data;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace New_Solution_Template.WebUI.Areas.Identity.Pages.Account
{
    [AllowAnonymous]
    public class LoginModel : PageModel
    {
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly ILogger<LoginModel> _logger;

        public LoginModel(SignInManager<ApplicationUser> signInManager, ILogger<LoginModel> logger)
        {
            _signInManager = signInManager;
            _logger = logger;
        }

        [BindProperty]
        public InputModel Input { get; set; }

        public IList<AuthenticationScheme> ExternalLogins { get; set; }

        public string ReturnUrl { get; set; }

        [TempData]
        public string ErrorMessage { get; set; }

        public class InputModel
        {
            [Required]
            [EmailAddress]
            public string Email { get; set; }

            [Required]
            [DataType(DataType.Password)]
            public string Password { get; set; }

            [Display(Name = "Remember me?")]
            public bool RememberMe { get; set; }
        }

        public async Task OnGetAsync(string returnUrl = null)
        {
            if (!string.IsNullOrEmpty(ErrorMessage))
            {
                ModelState.AddModelError(string.Empty, ErrorMessage);
            }

            returnUrl = returnUrl ?? Url.Content("~/");

            // Clear the existing external cookie to ensure a clean login process
            await HttpContext.SignOutAsync(IdentityConstants.ExternalScheme);

            ExternalLogins = (await _signInManager.GetExternalAuthenticationSchemesAsync()).ToList();

            ReturnUrl = returnUrl;
        }

        public async Task<IActionResult> OnPostAsync(string returnUrl = null)
        {
            returnUrl = returnUrl ?? Url.Content("~/");

            if (ModelState.IsValid)
            {
                // This doesn't count login failures towards account lockout
                // To enable password failures to trigger account lockout, set lockoutOnFailure: true
                var result = await _signInManager.PasswordSignInAsync(Input.Email, Input.Password, Input.RememberMe, lockoutOnFailure: true);
                if (result.Succeeded)
                {
                    _logger.LogInformation("User logged in.");
                    return LocalRedirect(returnUrl);
                }
                if (result.RequiresTwoFactor)
                {
                    return RedirectToPage("./LoginWith2fa", new { ReturnUrl = returnUrl, RememberMe = Input.RememberMe });
                }
                if (result.IsLockedOut)
                {
                    _logger.LogWarning("User account locked out.");
                    return RedirectToPage("./Lockout");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Invalid login attempt.");
                    return Page();
                }
            }

            // If we got this far, something failed, redisplay form
            return Page();
        }
    }
}

New_Solution_Template.WebUI/Controllers/AccountsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DataTablesParser;
//using New_Solution_Template.Data.Entity;
using Microsoft.AspNetCore.Mvc;
using New_Solution_Template.Services;
using New_Solution_Template.Data;
using Mapster;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace New_Solution_Template.WebUI.Controllers
{
    public class AccountsController : Controller
    {
        private readonly IAccountService _accountService;
        private readonly ILogger<AccountService> _logger;

        public AccountsController(IAccountService accountService,
            ILogger<AccountService> logger
            )
        {
            _accountService = accountService;
            _logger = logger;
        }
        public IActionResult Index()
        {
            return View();
        }
   [HttpPost]
        public IActionResult GetDatatableSource()
        {
            var parser = new Parser<ApplicationUser>(Request.Form, _accountService.GetAll());
            return Json(parser.Parse());
        }


        [HttpGet]
        public async Task<ActionResult> GetUsers(string userReferenceIds, string search = "", int page = 1)
        {
            try
            {
                int dataCountPerPage = 10;

                //find
                IQueryable<ApplicationUser> query = null;

                query = _accountService.GetActiveUsers();

                dynamic data = new dynamic[] { };

                if (query != null)
                {
                    query = query.OrderByDescending(a => a.FirstName).ThenByDescending(a => a.EmploymentDate);

                   if (!string.IsNullOrWhiteSpace(search))
                    {
                        query = query.Where(a => a.UserName.Contains(search) || a.FirstName.Contains(search) || a.LastName.Contains(search));
                    }

                    //skip-take
                    query = query.Skip((page - 1) * dataCountPerPage).Take(dataCountPerPage);

                    //map result
                    data = (await query.ToListAsync()).Select(a => new
                    {
                        text = a.FullName,
                        date = a.EmploymentDate,
                        id = a.Id
                    });
                }

                return Json(data);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "GetPushActionReferences could not be retrived data. search:{search} page:{page}", search, page);
            }

            return Json(new {  });
        }
    }
}

New_Solution_Template.WebUI/Views/Accounts/Index.cshtml
@{
    ViewData["Title"] = "Çalışanlar";
}
<h1>Çalışanlar</h1>

<div>
    <table class="table dataTable">
        <tfoot>
            <tr>
                <th rowspan="1" colspan="1" width="20%"><input type="text" name="search_FirstName" placeholder="Ara: Adı" class="form-control" /></th>
                <th rowspan="1" colspan="1" width="20%"><input type="text" name="search_LastName" placeholder="Ara: Soyadı" class="form-control" /></th>
                <th rowspan="1" colspan="1" width="20%"><input type="text" name="search_EmploymentDate" placeholder="Ara: İşe Başlangıç Tarihi" class="form-control cursorPointer date-search-selector" readonly="readonly" /></th>
                <th rowspan="1" colspan="1" width="20%"><input type="text" name="search_UnemploymentDate" placeholder="Ara: İşten Ayrılma Tarihi" class="form-control cursorPointer date-search-selector" readonly="readonly" /></th>

            </tr>
        </tfoot>
    </table>
</div>
<table id="oTable" class="table">
    <thead>
        <tr>
            <th>
                Adı
            </th>
            <th>
                Soyadı
            </th>
            <th>
                Departman
            </th>
            <th>
                İşe Başlangıç Tarihi
            </th>
            <th>
                İşten Ayrılma Tarihi
            </th>
            <th>Yöneticisi</th>
            <th>
                Aktif
            </th>
            <th>
                Silindi
            </th>
            <th></th>
        </tr>
    </thead>
</table>
@section Scripts{
    <script type="text/javascript">

        $(document).ready(function () {
            oTable = $('#oTable').DataTable({
                serverSide: true,
                processing: true,
                ajax: {
                    url: '@Url.Action("GetDatatableSource", "Accounts", null,Context.Request.Scheme, null)',
                    type: 'POST',
                },
                pagingType: "full_numbers",
                buttons: ['copy', 'excel', 'pdf'],
                columns: [
                    { data: "FirstName", title: "Adı", name: "FirstName" },
                    { data: "LastName", title: "Soyadı", name: "LastName" },
                    { data: "Department", title: "Departman", name: "Department" },
                    { data: "EmploymentDate", title: "İşe Başlangıç Tarihi", name: "EmploymentDate" },
                    { data: "UnemploymentDate", title: "İşten Ayrılma Tarihi", name: "UnemploymentDate" },
                    //{ data: "Parent.FullName", title: "Yöneticisi", name: "Parent.FullName" },
                    { data: "IsActive", title: "Aktif", "render": renderBoolean, "className": "dt-right" },
                    { data: "IsDeleted", title: "Silindi", "render": renderBoolean, "className": "dt-right" },
                    { data: "Id", title: "", sortable: false, "className": "dt-right", render: function (id, type, row) { return '<a href="Accounts/Save/' + id + '" class="fa fa-edit" title="Edit"></a>' } },
                    { data: "Id", title: "", sortable: false, "className": "dt-right", render: function (id, type, row) { return '<a href="Accounts/Delete/' + id + '" class="fa fa-trash" title="Delete" onclick="confirm("Are you sure you want to delete ...?")"></a>' } }
                ],
                "sDom": 'r<"datatable-header"><"datatable-scroll"t><"datatable-footer text-center"p<"clear"<"fl"i><"fr"l>>>',
            });
        });
    </script>
}